name: Pipeline para Deploy da aplicação no AWS

on:
   push:
     branches:
        - main
   pull_request:
     branches:
        - main   
    
    deploy:
        name: Publicação
        runs-on: ubuntu-22.04
        needs: test
        steps:
          
           - name: Checkout code
             uses: actions/checkout@v2

           - name: Download JAR artifact
             uses: actions/download-artifact@v4
             with:
                name: jar-file

           - name: Listar artefatos baixados
             run: ls -la

           - name: Renomear arquivo JAR
             run: |
               JAR_FILE=$(ls *.jar)
               echo "Arquivo JAR baixado: $JAR_FILE"
               mv $JAR_FILE api-java-aws.jar

           - name: Fazer deploy no Elastic Beanstalk
             uses: einaregilsson/beanstalk-deploy@v20
             with:
                 aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
                 aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                 application_name: api-java-aws
                 environment_name: Api-javai-aws-env
                 region: us-east-2
                 deployment_package: api-java-aws.jar
                 version_label: ${{ github.sha }}


          # Limpar artefatos após o deploy
           - name: Limpar arquivos temporários
             run: rm -f *.jar
